repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-yaml
      - id: no-commit-to-branch
        args: [--branch, master]

  - repo: https://github.com/pycqa/isort
    rev: 5.11.3
    hooks:
      - id: isort
        name: isort
        description: isort enforcement
        entry: isort
        language: python
        types: [python]
        exclude: (migrations|tests|alembic)
        args: [--settings, setup.cfg]

  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
        name: black
        description: format the code using black
        entry: black app/
        language: python
        types: [python]
        exclude: (migrations|config/settings/|tests|alembic)
        args: [--line-length=79]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: flake8
        description: linting the code using flake8
        entry: flake8 app/
        language: python
        types: [python]
        args: [--config, setup.cfg]
