version: "3.9"

services:
  app:
    restart: always
    build: .
    command: sh -c 'python main.py'
    container_name: qrcats
    volumes:
      - volume_app:/app
    env_file:
      - app/.env

volumes:
  volume_app:
