version: "3.9"

services:
  app:
    restart: always
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    container_name: qrcats
    volumes:
      - volume_app:/app
    env_file:
      - .env
    ports:
      - 80:80

volumes:
  volume_app:
